# Generated by Django 3.0.3 on 2020-03-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buidling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='楼层名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='楼层图片')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='市')),
                ('area', models.CharField(blank=True, max_length=32, null=True, verbose_name='区')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '楼层管理',
                'verbose_name_plural': '楼层管理',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='设备类型名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='设备类型图片')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '类型管理',
                'verbose_name_plural': '类型管理',
            },
        ),
        migrations.CreateModel(
            name='Parms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='参数名')),
                ('key', models.CharField(max_length=50, verbose_name='参数key')),
                ('value', models.CharField(max_length=50, verbose_name='参数值')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '参数管理',
                'verbose_name_plural': '参数管理',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分组名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='分组图片')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='device.Buidling', verbose_name='所属楼层')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '分组管理',
                'verbose_name_plural': '分组管理',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='设备名称')),
                ('sn', models.CharField(db_index=True, max_length=64, verbose_name='设备网关编码')),
                ('num', models.CharField(max_length=32, verbose_name='设备地址位')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备地址')),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', '在线'), ('0', '离线')], default=0, max_length=50, verbose_name='在离线状态')),
                ('switch', models.CharField(choices=[('1', '打开'), ('0', '关闭')], default=0, max_length=50, verbose_name='开关状态')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('param1', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数1')),
                ('param2', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数2')),
                ('param3', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数3')),
                ('param4', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数4')),
                ('param5', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数5')),
                ('param6', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数6')),
                ('param7', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数7')),
                ('param8', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数8')),
                ('param9', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数9')),
                ('param10', models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数10')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='device.Buidling', verbose_name='所属楼层')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='device.Group', verbose_name='所属分组')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='device.DeviceType', verbose_name='设备类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备管理',
            },
        ),
    ]
