# Generated by Django 3.0.3 on 2020-03-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200309_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='lng1',
            new_name='lng',
        ),
    ]
