# Generated by Django 3.0.3 on 2020-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20200309_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='tag',
            field=models.CharField(choices=[('0', 'stateraw'), ('1', 'state')], default='0', max_length=1, verbose_name='订阅方式'),
        ),
    ]
