# Generated by Django 3.0.3 on 2020-05-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_devicetype_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='param11',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数11'),
        ),
    ]
