# Generated by Django 3.0.3 on 2020-05-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_devices_param11'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='ldce',
            field=models.BooleanField(default=False, verbose_name='是否漏电测试按钮'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='pele',
            field=models.BooleanField(default=False, verbose_name='是否存在漏电流'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='sdxz',
            field=models.BooleanField(default=False, verbose_name='是否上电状态选择'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='temp',
            field=models.BooleanField(default=False, verbose_name='是否存在温度'),
        ),
    ]
