# Generated by Django 3.0.3 on 2020-05-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20200509_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
