# Generated by Django 3.0.3 on 2020-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20200516_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='param12',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数12'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param13',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数13'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param14',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数14'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param15',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数15'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param16',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数16'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param17',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数17'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param18',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数18'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param19',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数19'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param20',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数20'),
        ),
        migrations.AddField(
            model_name='devices',
            name='param21',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备用参数21'),
        ),
    ]
