# Generated by Django 3.0.3 on 2020-03-09 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_count', models.BigIntegerField(blank=True, null=True, verbose_name='设备总数')),
                ('online_count', models.BigIntegerField(blank=True, null=True, verbose_name='在线总数')),
                ('power', models.FloatField(blank=True, null=True, verbose_name='总功率')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicecount', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
