# Generated by Django 3.0.3 on 2020-06-14 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200224_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
