# Generated by Django 3.0.3 on 2020-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_userinfo_addtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
