# Generated by Django 3.0.3 on 2020-06-17 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_role_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Department', verbose_name='所属部门'),
        ),
    ]
