# Generated by Django 3.0.3 on 2020-06-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_role_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, verbose_name='角色'),
        ),
    ]
