# Generated by Django 3.0.3 on 2020-06-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20200617_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Permission'),
        ),
    ]
