# Generated by Django 3.0.3 on 2020-05-01 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0004_devicetype_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='warnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnname', models.CharField(max_length=50, verbose_name='告警类型名称')),
                ('warnAddr', models.IntegerField(blank=True, null=True, verbose_name='主动告警标示位')),
                ('warnFrom', models.CharField(choices=[('0', '设备主动告警'), ('1', '系统设置告警')], max_length=32, verbose_name='告警来源')),
                ('uplimit', models.FloatField(blank=True, null=True, verbose_name='系统告警上限阀值')),
                ('downlimit', models.FloatField(blank=True, null=True, verbose_name='系统告警下限阀值')),
                ('is_able', models.BooleanField(default=False, verbose_name='是否启用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warntype', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='warndata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='告警时间')),
                ('warnEle', models.FloatField(blank=True, null=True, verbose_name='告警时电流信息')),
                ('warnVol', models.FloatField(blank=True, null=True, verbose_name='告警时电压信息')),
                ('warnPower', models.FloatField(blank=True, null=True, verbose_name='告警时功率信息')),
                ('warnHz', models.FloatField(blank=True, null=True, verbose_name='告警时频率')),
                ('warntEle', models.FloatField(blank=True, null=True, verbose_name='告警时有功电度量')),
                ('warnpEle', models.FloatField(blank=True, null=True, verbose_name='告警时漏电流')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warndata', to='device.Devices', verbose_name='设备信息')),
                ('warnType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warndata', to='warndata.warnType', verbose_name='告警类型')),
            ],
        ),
    ]
