# Generated by Django 3.0.3 on 2020-05-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warndata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warntype',
            name='addtime',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
