# Generated by Django 3.0.3 on 2020-05-01 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warndata', '0002_warntype_addtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warntype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warntype', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
