# Generated by Django 3.0.3 on 2020-05-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warndata', '0003_auto_20200501_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warntype',
            name='addtime',
        ),
    ]
