# Generated by Django 3.0.3 on 2020-05-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0004_devicetype_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(verbose_name='上报时间')),
                ('meaEle', models.FloatField(blank=True, null=True, verbose_name='电流')),
                ('meaVol', models.FloatField(blank=True, null=True, verbose_name='电压')),
                ('tPower', models.FloatField(blank=True, null=True, verbose_name='功率')),
                ('meaHz', models.FloatField(blank=True, null=True, verbose_name='频率')),
                ('tEle', models.FloatField(blank=True, null=True, verbose_name='有功电度量')),
                ('pEle', models.FloatField(blank=True, null=True, verbose_name='漏电流')),
                ('params1', models.FloatField(blank=True, null=True, verbose_name='备用参数1')),
                ('params2', models.FloatField(blank=True, null=True, verbose_name='备用参数2')),
                ('params3', models.FloatField(blank=True, null=True, verbose_name='备用参数3')),
                ('params4', models.FloatField(blank=True, null=True, verbose_name='备用参数4')),
                ('params5', models.FloatField(blank=True, null=True, verbose_name='备用参数5')),
                ('params6', models.FloatField(blank=True, null=True, verbose_name='备用参数6')),
                ('params7', models.FloatField(blank=True, null=True, verbose_name='备用参数7')),
                ('params8', models.FloatField(blank=True, null=True, verbose_name='备用参数8')),
                ('params9', models.FloatField(blank=True, null=True, verbose_name='备用参数9')),
                ('params10', models.FloatField(blank=True, null=True, verbose_name='备用参数10')),
                ('params11', models.FloatField(blank=True, null=True, verbose_name='备用参数11')),
                ('params12', models.FloatField(blank=True, null=True, verbose_name='备用参数12')),
                ('params13', models.FloatField(blank=True, null=True, verbose_name='备用参数13')),
                ('switchstate', models.IntegerField(choices=[(0, '合闸'), (1, '分闸')], verbose_name='设备开关状态')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtimedata', to='device.Devices', verbose_name='实时数据')),
            ],
            options={
                'verbose_name': '实时历史数据',
                'verbose_name_plural': '实时历史数据',
            },
        ),
        migrations.CreateModel(
            name='GroupHourDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(verbose_name='计算时间')),
                ('tEle', models.FloatField(blank=True, null=True, verbose_name='有功电度量')),
                ('pay', models.FloatField(blank=True, null=True, verbose_name='电费')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouphourdegree', to='device.Group', verbose_name='分组每小时电度量')),
            ],
            options={
                'verbose_name': '每小时电度量',
                'verbose_name_plural': '每小时电度量',
            },
        ),
        migrations.CreateModel(
            name='DeviceHourDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(verbose_name='计算时间')),
                ('ele', models.FloatField(blank=True, null=True, verbose_name='电量')),
                ('pay', models.FloatField(blank=True, null=True, verbose_name='电费')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicehourdegree', to='device.Devices', verbose_name='设备每小时电度量')),
            ],
            options={
                'verbose_name': '每小时电度量',
                'verbose_name_plural': '每小时电度量',
            },
        ),
        migrations.CreateModel(
            name='BuildingHourDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(verbose_name='计算时间')),
                ('tEle', models.FloatField(blank=True, null=True, verbose_name='有功电度量')),
                ('pay', models.FloatField(blank=True, null=True, verbose_name='电费')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildinghourdegree', to='device.Buidling', verbose_name='楼层每小时电度量')),
            ],
            options={
                'verbose_name': '每小时电度量',
                'verbose_name_plural': '每小时电度量',
            },
        ),
        migrations.CreateModel(
            name='ActualDataTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPower', models.BigIntegerField(verbose_name='总功率')),
                ('addTime', models.DateTimeField(verbose_name='统计时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualdatatotal', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户功率统计',
                'verbose_name_plural': '用户功率统计',
            },
        ),
        migrations.CreateModel(
            name='ActualDataGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPower', models.BigIntegerField(verbose_name='总功率')),
                ('addTime', models.DateTimeField(verbose_name='统计时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualdatagroup', to='device.Group', verbose_name='所属分组')),
            ],
            options={
                'verbose_name': '分组功率统计',
                'verbose_name_plural': '分组功率统计',
            },
        ),
        migrations.CreateModel(
            name='ActualDataBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPower', models.BigIntegerField(verbose_name='总功率')),
                ('addTime', models.DateTimeField(verbose_name='统计时间')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualdatabuild', to='device.Buidling', verbose_name='所属楼层')),
            ],
            options={
                'verbose_name': '楼层功率统计',
                'verbose_name_plural': '楼层功率统计',
            },
        ),
        migrations.CreateModel(
            name='ActualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(verbose_name='上报时间')),
                ('meaEle', models.FloatField(blank=True, null=True, verbose_name='电流')),
                ('meaVol', models.FloatField(blank=True, null=True, verbose_name='电压')),
                ('tPower', models.FloatField(blank=True, null=True, verbose_name='功率')),
                ('meaHz', models.FloatField(blank=True, null=True, verbose_name='频率')),
                ('tEle', models.FloatField(blank=True, null=True, verbose_name='有功电度量')),
                ('pEle', models.FloatField(blank=True, null=True, verbose_name='漏电流')),
                ('params1', models.FloatField(blank=True, null=True, verbose_name='备用参数1')),
                ('params2', models.FloatField(blank=True, null=True, verbose_name='备用参数2')),
                ('params3', models.FloatField(blank=True, null=True, verbose_name='备用参数3')),
                ('params4', models.FloatField(blank=True, null=True, verbose_name='备用参数4')),
                ('params5', models.FloatField(blank=True, null=True, verbose_name='备用参数5')),
                ('params6', models.FloatField(blank=True, null=True, verbose_name='备用参数6')),
                ('params7', models.FloatField(blank=True, null=True, verbose_name='备用参数7')),
                ('params8', models.FloatField(blank=True, null=True, verbose_name='备用参数8')),
                ('params9', models.FloatField(blank=True, null=True, verbose_name='备用参数9')),
                ('params10', models.FloatField(blank=True, null=True, verbose_name='备用参数10')),
                ('params11', models.FloatField(blank=True, null=True, verbose_name='备用参数11')),
                ('params12', models.FloatField(blank=True, null=True, verbose_name='备用参数12')),
                ('params13', models.FloatField(blank=True, null=True, verbose_name='备用参数13')),
                ('switchstate', models.IntegerField(choices=[(0, '合闸'), (1, '分闸')], verbose_name='设备开关状态')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualdatahistory', to='device.Devices', verbose_name='实时历史数据')),
            ],
            options={
                'verbose_name': '实时数据',
                'verbose_name_plural': '实时数据',
            },
        ),
    ]
