# Generated by Django 3.0.3 on 2020-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualdata',
            name='params14',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数4'),
        ),
        migrations.AddField(
            model_name='actualdata',
            name='params15',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数5'),
        ),
        migrations.AddField(
            model_name='actualdata',
            name='params16',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数6'),
        ),
        migrations.AddField(
            model_name='actualdata',
            name='params17',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数7'),
        ),
        migrations.AddField(
            model_name='actualdata',
            name='params18',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数8'),
        ),
        migrations.AddField(
            model_name='actualdata',
            name='params19',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数9'),
        ),
        migrations.AddField(
            model_name='actualdata',
            name='params20',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数10'),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='params14',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数4'),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='params15',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数5'),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='params16',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数6'),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='params17',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数7'),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='params18',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数8'),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='params19',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数9'),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='params20',
            field=models.FloatField(blank=True, null=True, verbose_name='备用参数10'),
        ),
    ]
