# Generated by Django 3.0.3 on 2020-03-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0003_auto_20200309_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kai1', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('guan1', models.CharField(max_length=32, verbose_name='定时1关时间')),
                ('kai2', models.CharField(max_length=32, verbose_name='定时2开时间')),
                ('guan2', models.CharField(max_length=32, verbose_name='定时2关时间')),
                ('chongfu', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('glys1', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('glys2', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('yjf', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('fz_01', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('fz_02', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('yjdf', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('dfjg', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('gldz', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('zdgldz', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('gdydz', models.CharField(max_length=32, verbose_name='定时1开时间')),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='device.Devices', verbose_name='参数管理')),
            ],
            options={
                'verbose_name': '下发参数管理',
                'verbose_name_plural': '下发参数管理',
            },
        ),
    ]
