# Generated by Django 3.0.3 on 2020-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20200313_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceparams',
            name='ddydz',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='定时1开时间'),
        ),
    ]
