# Generated by Django 3.0.3 on 2020-05-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_deviceparams_ddydz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceparams',
            name='ddydz',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='低电压定值'),
        ),
        migrations.AlterField(
            model_name='deviceparams',
            name='fz_01',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='0区复制1'),
        ),
        migrations.AlterField(
            model_name='deviceparams',
            name='fz_02',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='0区复制2'),
        ),
        migrations.AlterField(
            model_name='deviceparams',
            name='gdydz',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='过电压定值'),
        ),
    ]
